### ISSUE TITLE
mac下执行没效果

### ISSUE THREAD

**Issue by Malenconiaprincep** [jf3096/wx-compile-key#1]
gulp.task(`wx:autoCompile`, autoCompileGulpTask);

```
gulp.task('watch', function() {
  gulp.watch(Asset.js, ['parseJs']);
  gulp.watch(Asset.sass, ['parseSass']);
  gulp.watch(Asset.wxml, ['parseWxml']);
  gulp.watch(Asset.json, ['parseJson']);
  gulp.watch(Asset.js, ['wx:autoCompile'])
});
```

但开发工具不会重新执行编译

我监听js文件 来触发任务

**Comment by jf3096** [comment]
@Malenconiaprincep  抱歉  没测试过mac, 这两天测试一下   给你反馈

**Comment by jf3096** [comment]
@Malenconiaprincep 我重新修改了一下策略, 应该能兼容mac和window, 而且更优, 不用担心冲突, 晚上测试好推送上去, 你可以描述一下你的问题吗?

**Comment by Malenconiaprincep** [comment]
不好意思 这么晚才回复你的问题    问题是修改后不会触发文件编译

**Comment by jf3096** [comment]
alpha版本写好了，  window测过通过， 今晚找个mac试试， 策略也改了  不需要按全局快捷键 自动编译  因为全局快捷键潜在被占用的可能，自己体验测试1周，决定抛弃。
